### ISSUE TITLE
[Bug] (node:5632) DeprecationWarning: Calling an asynchronous function without callback is deprecated.

### ISSUE THREAD

**Issue by Kristinita** [KonstantinKai/css-to-stylus-converter#1]
### 1. Summary

If I use CSS-To-Stylus via CLI, I get warning in console.

### 2. Settings

My `KristinaRainy.css` file:

```css
html {
    height: 100%;
}
```

### 3. Steps to reproduce

I print in terminal:

```shell
css-to-stylus --verbose KristinaRainy.css
```

### 4. Expected behavior

No warnings in terminal.

### 5. Actual behavior

```shell
D:\Киролайна\Тестовые файлы>css-to-stylus --verbose Sasha.css
  KristinaRainy.css -> KristinaRainy.styl
(node:5632) DeprecationWarning: Calling an asynchronous function without callback is deprecated.
```

### 6. Environment

**Operating system and version:**
Windows 10 Enterprise LTSB 64-bit EN
**Node.js:**
v7.10.0
**CSS-To-Stylus**
1.1.2

Thanks.

**Comment by KonstantinKai** [comment]
@Kristinita Fixed. 10x 👍
