### ISSUE TITLE
Properties that start with a dash are ignored

### ISSUE THREAD

**Issue by nachocab** [KonstantinKai/css-to-stylus-converter#2]
Hi Konstantin, 
Thanks for your extension. It's awesome!

The only bug I've noticed is the way it deals with properties that start with a dash, for example:

    input[type=checkbox]{-webkit-appearance:checkbox;}

This gets converted to

    input[type=checkbox]

Any idea about how to fix it?

**Comment by KonstantinKai** [comment]
Hi @nachocab! Thank you for your feedback and patience. I'm very sorry for my long feedback on this issue, I had a lot of holidays :smile::beers: I have fixed this problem and wrote the test. You can update your module or vs code extension.

**Comment by KonstantinKai** [comment]
Fixed in 1.1.9

**Comment by nachocab** [comment]
Awesome, thank you!!
